import Head from 'next/head';
import {useEffect,useState} from 'react';
import styles from '../../styles/PortalLogin.module.css';

const allowedDestinations=new Set(['/admin','/admin/articles']);
export default function AdminLogin(){
 const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const destination=typeof window==='undefined'?'/admin/articles':(allowedDestinations.has(new URLSearchParams(location.search).get('next'))?new URLSearchParams(location.search).get('next'):'/admin/articles');
 useEffect(()=>{fetch('/api/admin/session',{cache:'no-store'}).then(response=>{if(response.ok)location.replace(destination)}).catch(()=>{});},[destination]);
 const submit=async event=>{event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});if(!response.ok)throw new Error('The administrator key is incorrect or access is temporarily restricted.');setKey('');location.assign(destination);}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 return <><Head><title>Administrator Login | TrustStack Academy</title><meta name="robots" content="noindex,nofollow"/></Head><main className={`${styles.page} ${styles.admin}`}><div className={styles.shell}><section className={styles.story}><a className={styles.brand} href="/home.html"><img src="/truststack-home-logo.png" alt="TrustStack Academy"/><span>TrustStack Academy</span></a><div className={styles.eyebrow}>AUTHORIZED PERSONNEL ONLY</div><h1>Publish with control and confidence.</h1><p>Secure access to TrustStack Academy editorial publishing and credential administration.</p><div className={styles.trust}><span>SECURE SESSION</span><span>AUDITED ACTIONS</span><span>ONE-HOUR ACCESS</span></div></section><section className={styles.panel}><small>ADMINISTRATOR PORTAL</small><h2>Protected access.</h2><p className={styles.intro}>Enter the administrator key. Your key is exchanged once for a secure, short-lived session.</p><form onSubmit={submit}><label className={styles.field}><span>ADMINISTRATOR KEY</span><input type="password" value={key} onChange={event=>setKey(event.target.value)} placeholder="Enter secure key" autoComplete="current-password" required autoFocus/></label><button className={styles.submit} disabled={busy}>{busy?'Securing session…':'Continue to publishing →'}</button></form>{message&&<div className={styles.notice}>{message}</div>}<div className={styles.help}>Access attempts are throttled. Never share the administrator key or enter it outside <strong>truststack.academy</strong>.</div><a className={styles.back} href="/home.html">← Return to public website</a></section></div></main></>;
}
