export const courseCatalog = [
  { slug:'soc-analyst', title:'SOC Analyst Track', icon:'🛡', color:'#00b8d9', level:'Beginner', summary:'Build the practical skills to monitor security events, investigate alerts and respond to incidents in a modern security operations centre.', tools:'Wazuh · Splunk · Wireshark · MITRE ATT&CK', modules:['SOC operations, roles and alert lifecycle','Windows, Linux and network log analysis','SIEM queries, dashboards and detection rules','Threat hunting with indicators and behaviour','Incident triage, escalation and playbooks','Capstone: live SOC investigation'] },
  { slug:'digital-forensics', title:'Digital Forensics', icon:'⌕', color:'#f97316', level:'Intermediate', summary:'Preserve evidence, reconstruct attacks and produce defensible findings through practical disk, memory and timeline investigations.', tools:'Autopsy · Volatility · FTK Imager · Wireshark', modules:['Evidence handling and chain of custody','Forensic imaging and integrity verification','File-system and deleted-file analysis','Memory acquisition and Volatility analysis','Timeline and network reconstruction','Capstone: investigation report'] },
  { slug:'threat-intelligence', title:'Threat Intelligence', icon:'◉', color:'#8b5cf6', level:'Intermediate', summary:'Turn threat data into actionable intelligence using structured analysis, adversary tracking and operational intelligence workflows.', tools:'MISP · OpenCTI · MITRE ATT&CK · OSINT', modules:['Intelligence lifecycle and requirements','OSINT collection and source validation','Indicators, TTPs and ATT&CK mapping','Threat actor and campaign analysis','Intelligence reporting and dissemination','Capstone: intelligence assessment'] },
  { slug:'penetration-testing', title:'Penetration Testing', icon:'◎', color:'#ef4444', level:'Advanced', summary:'Learn an authorised penetration-testing methodology from reconnaissance and exploitation through remediation-focused reporting.', tools:'Nmap · Burp Suite · Metasploit · Kali Linux', modules:['Scoping, rules of engagement and methodology','Reconnaissance and service enumeration','Vulnerability validation and exploitation','Web and API security testing','Privilege escalation and lateral movement','Capstone: professional penetration-test report'] },
  { slug:'cloud-security', title:'Cloud Security', icon:'☁', color:'#0ea5e9', level:'Intermediate', summary:'Secure cloud identities, workloads and data across AWS and Azure using practical configuration reviews and detection labs.', tools:'AWS · Azure · Prowler · ScoutSuite', modules:['Shared responsibility and cloud architecture','IAM hardening and least privilege','Network, storage and secrets security','Cloud posture assessment and remediation','Cloud logging, detection and response','Capstone: secure cloud review'] },
  { slug:'governance-grc', title:'Governance & GRC', icon:'✓', color:'#10b981', level:'Beginner', summary:'Translate security and privacy obligations into practical policies, risks, controls, evidence and audit-ready improvement plans.', tools:'ISO 27001 · NIST CSF · NDPA · Risk Registers', modules:['Governance, risk and compliance foundations','Risk assessment and treatment planning','Policy and control design','NDPA and privacy compliance operations','Audit evidence and third-party risk','Capstone: security improvement plan'] },
  { slug:'malware-analysis', title:'Malware Analysis', icon:'⌁', color:'#f59e0b', level:'Advanced', summary:'Safely examine suspicious files, identify malicious behaviour and create useful detection artefacts in an isolated lab.', tools:'REMnux · FLARE-VM · Ghidra · YARA', modules:['Safe lab design and malware triage','Static analysis and file characteristics','Dynamic behavioural analysis','Windows internals and persistence','YARA rules and indicator development','Capstone: malware analysis report'] },
  { slug:'security-engineering', title:'Security Engineering', icon:'⌘', color:'#6366f1', level:'CAP-ADIT', summary:'Design and build secure systems by applying architecture, automation, application security and continuous assurance practices.', tools:'Threat Modelling · DevSecOps · SAST · IaC', modules:['Secure architecture and design principles','Threat modelling and security requirements','Secure development and code review','DevSecOps pipelines and automated testing','Infrastructure security and observability','Capstone: secure solution architecture'] },
];

export const courseBySlug = Object.fromEntries(courseCatalog.map((course) => [course.slug, course]));
